import type { InventoryDashboardData, RawMaterialInventoryItem, RawMaterialMovement, RawMaterialSortOption } from '@/app/types/inventory'

export const inventoryDashboardData: InventoryDashboardData = {
  health: {
    status: 'attention',
    score: 82,
    summary: 'Inventory is stable, with several raw materials needing replenishment soon.',
  },

  forecastWarningCount: 35,

  warehouseCapacity: {
    warehouse: 'Main warehouse',
    used: 6840,
    total: 10000,
  },

  movementVelocity: [
    { category: 'fast', label: 'Fast Movers', percentage: 68 },
    { category: 'stable', label: 'Stable', percentage: 22 },
    { category: 'slow', label: 'Slow / Stagnant', percentage: 10 },
  ],

  predictedStockouts: [
    {
      sku: 'RM-1005',
      product: 'Clear varnish',
      warehouse: 'ColorCraft Depot',
      availableUnits: 18,
      unit: 'cans',
      reorderPoint: 20,
      estimatedStockoutDate: 'Aug 18, 2026',
      risk: 'critical',
    },
    {
      sku: 'RM-1015',
      product: 'Contact cement',
      warehouse: 'BuildPro Supplies',
      availableUnits: 15,
      unit: 'cans',
      reorderPoint: 18,
      estimatedStockoutDate: 'Aug 19, 2026',
      risk: 'critical',
    },
    {
      sku: 'RM-1022',
      product: 'Particle boards',
      warehouse: 'Quezon Panel Mart',
      availableUnits: 21,
      unit: 'sheets',
      reorderPoint: 25,
      estimatedStockoutDate: 'Aug 20, 2026',
      risk: 'critical',
    },
    {
      sku: 'RM-1025',
      product: 'Epoxy adhesive',
      warehouse: 'BuildPro Supplies',
      availableUnits: 12,
      unit: 'kits',
      reorderPoint: 20,
      estimatedStockoutDate: 'Aug 21, 2026',
      risk: 'critical',
    },
    {
      sku: 'RM-1032',
      product: 'HDF sheets',
      warehouse: 'Quezon Panel Mart',
      availableUnits: 18,
      unit: 'sheets',
      reorderPoint: 22,
      estimatedStockoutDate: 'Aug 22, 2026',
      risk: 'critical',
    },
    {
      sku: 'RM-1042',
      product: 'Cement board',
      warehouse: 'Quezon Panel Mart',
      availableUnits: 14,
      unit: 'sheets',
      reorderPoint: 18,
      estimatedStockoutDate: 'Aug 23, 2026',
      risk: 'critical',
    },
    {
      sku: 'RM-1054',
      product: 'Wood primer',
      warehouse: 'ColorCraft Depot',
      availableUnits: 17,
      unit: 'cans',
      reorderPoint: 20,
      estimatedStockoutDate: 'Aug 24, 2026',
      risk: 'critical',
    },
    {
      sku: 'RM-1064',
      product: 'Wood wax',
      warehouse: 'ColorCraft Depot',
      availableUnits: 13,
      unit: 'cans',
      reorderPoint: 18,
      estimatedStockoutDate: 'Aug 25, 2026',
      risk: 'critical',
    },
    {
      sku: 'RM-1067',
      product: 'Melamine boards',
      warehouse: 'Quezon Panel Mart',
      availableUnits: 19,
      unit: 'sheets',
      reorderPoint: 24,
      estimatedStockoutDate: 'Aug 26, 2026',
      risk: 'critical',
    },
    {
      sku: 'RM-1074',
      product: 'Sanding sealer',
      warehouse: 'ColorCraft Depot',
      availableUnits: 16,
      unit: 'cans',
      reorderPoint: 20,
      estimatedStockoutDate: 'Aug 27, 2026',
      risk: 'critical',
    },
    {
      sku: 'RM-1077',
      product: 'Fire-rated plywood',
      warehouse: 'Quezon Panel Mart',
      availableUnits: 12,
      unit: 'sheets',
      reorderPoint: 15,
      estimatedStockoutDate: 'Aug 28, 2026',
      risk: 'critical',
    },
    {
      sku: 'RM-1082',
      product: 'Hardboard sheets',
      warehouse: 'Quezon Panel Mart',
      availableUnits: 17,
      unit: 'sheets',
      reorderPoint: 20,
      estimatedStockoutDate: 'Aug 29, 2026',
      risk: 'critical',
    },
    {
      sku: 'RM-1095',
      product: 'Spray adhesive',
      warehouse: 'BuildPro Supplies',
      availableUnits: 14,
      unit: 'cans',
      reorderPoint: 20,
      estimatedStockoutDate: 'Aug 30, 2026',
      risk: 'critical',
    },
    {
      sku: 'RM-1102',
      product: 'Insulation boards',
      warehouse: 'Quezon Panel Mart',
      availableUnits: 16,
      unit: 'sheets',
      reorderPoint: 20,
      estimatedStockoutDate: 'Aug 31, 2026',
      risk: 'critical',
    },

    // LOW STOCK / ATTENTION
    {
      sku: 'RM-1003',
      product: 'Steel brackets',
      warehouse: 'Metro Metalworks',
      availableUnits: 224,
      unit: 'pcs',
      reorderPoint: 180,
      estimatedStockoutDate: 'Sep 01, 2026',
      risk: 'attention',
    },
    {
      sku: 'RM-1004',
      product: 'Wood glue',
      warehouse: 'BuildPro Supplies',
      availableUnits: 32,
      unit: 'bottles',
      reorderPoint: 24,
      estimatedStockoutDate: 'Sep 02, 2026',
      risk: 'attention',
    },
    {
      sku: 'RM-1012',
      product: 'MDF panels',
      warehouse: 'Quezon Panel Mart',
      availableUnits: 38,
      unit: 'sheets',
      reorderPoint: 35,
      estimatedStockoutDate: 'Sep 03, 2026',
      risk: 'attention',
    },
    {
      sku: 'RM-1013',
      product: 'Cabinet hinges',
      warehouse: 'Metro Metalworks',
      availableUnits: 96,
      unit: 'pairs',
      reorderPoint: 80,
      estimatedStockoutDate: 'Sep 04, 2026',
      risk: 'attention',
    },
    {
      sku: 'RM-1017',
      product: 'Birch plywood',
      warehouse: 'Quezon Panel Mart',
      availableUnits: 27,
      unit: 'sheets',
      reorderPoint: 25,
      estimatedStockoutDate: 'Sep 05, 2026',
      risk: 'attention',
    },
    {
      sku: 'RM-1020',
      product: 'Machine screws',
      warehouse: 'Manila Hardware Co.',
      availableUnits: 430,
      unit: 'pcs',
      reorderPoint: 350,
      estimatedStockoutDate: 'Sep 06, 2026',
      risk: 'attention',
    },
    {
      sku: 'RM-1028',
      product: 'Chair legs',
      warehouse: 'Cavite Woodcraft',
      availableUnits: 19,
      unit: 'sets',
      reorderPoint: 20,
      estimatedStockoutDate: 'Sep 07, 2026',
      risk: 'attention',
    },
    {
      sku: 'RM-1035',
      product: 'Construction adhesive',
      warehouse: 'BuildPro Supplies',
      availableUnits: 26,
      unit: 'tubes',
      reorderPoint: 30,
      estimatedStockoutDate: 'Sep 08, 2026',
      risk: 'attention',
    },
    {
      sku: 'RM-1040',
      product: 'Carriage bolts',
      warehouse: 'Manila Hardware Co.',
      availableUnits: 190,
      unit: 'pcs',
      reorderPoint: 220,
      estimatedStockoutDate: 'Sep 09, 2026',
      risk: 'attention',
    },
    {
      sku: 'RM-1044',
      product: 'Gloss varnish',
      warehouse: 'ColorCraft Depot',
      availableUnits: 22,
      unit: 'cans',
      reorderPoint: 20,
      estimatedStockoutDate: 'Sep 10, 2026',
      risk: 'attention',
    },
    {
      sku: 'RM-1048',
      product: 'Bench legs',
      warehouse: 'Cavite Woodcraft',
      availableUnits: 16,
      unit: 'sets',
      reorderPoint: 18,
      estimatedStockoutDate: 'Sep 11, 2026',
      risk: 'attention',
    },
    {
      sku: 'RM-1052',
      product: 'PVC sheets',
      warehouse: 'Quezon Panel Mart',
      availableUnits: 28,
      unit: 'sheets',
      reorderPoint: 30,
      estimatedStockoutDate: 'Sep 12, 2026',
      risk: 'attention',
    },
    {
      sku: 'RM-1057',
      product: 'Phenolic board',
      warehouse: 'Quezon Panel Mart',
      availableUnits: 23,
      unit: 'sheets',
      reorderPoint: 25,
      estimatedStockoutDate: 'Sep 13, 2026',
      risk: 'attention',
    },
    {
      sku: 'RM-1061',
      product: 'Walnut boards',
      warehouse: 'Luzon Timber Supply',
      availableUnits: 26,
      unit: 'boards',
      reorderPoint: 22,
      estimatedStockoutDate: 'Sep 14, 2026',
      risk: 'attention',
    },
    {
      sku: 'RM-1070',
      product: 'Toggle bolts',
      warehouse: 'Manila Hardware Co.',
      availableUnits: 175,
      unit: 'pcs',
      reorderPoint: 200,
      estimatedStockoutDate: 'Sep 15, 2026',
      risk: 'attention',
    },
    {
      sku: 'RM-1085',
      product: 'Rubber adhesive',
      warehouse: 'BuildPro Supplies',
      availableUnits: 19,
      unit: 'cans',
      reorderPoint: 22,
      estimatedStockoutDate: 'Sep 16, 2026',
      risk: 'attention',
    },
    {
      sku: 'RM-1088',
      product: 'Desk legs',
      warehouse: 'Cavite Woodcraft',
      availableUnits: 22,
      unit: 'sets',
      reorderPoint: 25,
      estimatedStockoutDate: 'Sep 17, 2026',
      risk: 'attention',
    },
    {
      sku: 'RM-1092',
      product: 'Composite panels',
      warehouse: 'Quezon Panel Mart',
      availableUnits: 25,
      unit: 'sheets',
      reorderPoint: 28,
      estimatedStockoutDate: 'Sep 18, 2026',
      risk: 'attention',
    },
    {
      sku: 'RM-1094',
      product: 'Polyurethane finish',
      warehouse: 'ColorCraft Depot',
      availableUnits: 20,
      unit: 'cans',
      reorderPoint: 22,
      estimatedStockoutDate: 'Sep 19, 2026',
      risk: 'attention',
    },
    {
      sku: 'RM-1105',
      product: 'Wood filler',
      warehouse: 'BuildPro Supplies',
      availableUnits: 23,
      unit: 'tubes',
      reorderPoint: 25,
      estimatedStockoutDate: 'Sep 20, 2026',
      risk: 'attention',
    },
    {
      sku: 'RM-1110',
      product: 'Flange nuts',
      warehouse: 'Manila Hardware Co.',
      availableUnits: 155,
      unit: 'pcs',
      reorderPoint: 180,
      estimatedStockoutDate: 'Sep 21, 2026',
      risk: 'attention',
    },
  ],
}

export const mockRawMaterials: RawMaterialInventoryItem[] = [
  { id: 'RM-1001', productId: 'PRD-5001', material: 'Wood screws', category: 'Fasteners', quantity: 1280, unit: 'pcs', reorderPoint: 500, warehouse: 'Manila Hardware Co.', unitCost: 1.8, status: 'In stock' },
  { id: 'RM-1002', productId: 'PRD-5002', material: 'Oak boards', category: 'Lumber', quantity: 86, unit: 'boards', reorderPoint: 40, warehouse: 'Luzon Timber Supply', unitCost: 740, status: 'In stock' },
  { id: 'RM-1003', productId: 'PRD-5003', material: 'Steel brackets', category: 'Hardware', quantity: 224, unit: 'pcs', reorderPoint: 180, warehouse: 'Metro Metalworks', unitCost: 38, status: 'Low stock' },
  { id: 'RM-1004', productId: 'PRD-5004', material: 'Wood glue', category: 'Adhesives', quantity: 32, unit: 'bottles', reorderPoint: 24, warehouse: 'BuildPro Supplies', unitCost: 185, status: 'Low stock' },
  { id: 'RM-1005', productId: 'PRD-5005', material: 'Clear varnish', category: 'Finishing', quantity: 18, unit: 'cans', reorderPoint: 20, warehouse: 'ColorCraft Depot', unitCost: 420, status: 'Critical' },
  { id: 'RM-1006', productId: 'PRD-5006', material: 'Plywood sheets', category: 'Panels', quantity: 64, unit: 'sheets', reorderPoint: 30, warehouse: 'Quezon Panel Mart', unitCost: 1180, status: 'In stock' },
  { id: 'RM-1007', productId: 'PRD-5007', material: 'Drawer slides', category: 'Hardware', quantity: 140, unit: 'pairs', reorderPoint: 70, warehouse: 'Metro Metalworks', unitCost: 260, status: 'In stock' },
  { id: 'RM-1008', productId: 'PRD-5008', material: 'Table legs', category: 'Components', quantity: 48, unit: 'pcs', reorderPoint: 24, warehouse: 'Cavite Woodcraft', unitCost: 390, status: 'In stock' },
  { id: 'RM-1009', productId: 'PRD-5009', material: 'Sanding discs', category: 'Consumables', quantity: 520, unit: 'pcs', reorderPoint: 180, warehouse: 'BuildPro Supplies', unitCost: 12, status: 'In stock' },
  { id: 'RM-1010', productId: 'PRD-5010', material: 'Hex bolts', category: 'Fasteners', quantity: 760, unit: 'pcs', reorderPoint: 300, warehouse: 'Manila Hardware Co.', unitCost: 4.5, status: 'In stock' },

  { id: 'RM-1011', productId: 'PRD-5011', material: 'Pine boards', category: 'Lumber', quantity: 112, unit: 'boards', reorderPoint: 50, warehouse: 'Luzon Timber Supply', unitCost: 520, status: 'In stock' },
  { id: 'RM-1012', productId: 'PRD-5012', material: 'MDF panels', category: 'Panels', quantity: 38, unit: 'sheets', reorderPoint: 35, warehouse: 'Quezon Panel Mart', unitCost: 860, status: 'Low stock' },
  { id: 'RM-1013', productId: 'PRD-5013', material: 'Cabinet hinges', category: 'Hardware', quantity: 96, unit: 'pairs', reorderPoint: 80, warehouse: 'Metro Metalworks', unitCost: 85, status: 'Low stock' },
  { id: 'RM-1014', productId: 'PRD-5014', material: 'Wood stain', category: 'Finishing', quantity: 42, unit: 'cans', reorderPoint: 20, warehouse: 'ColorCraft Depot', unitCost: 350, status: 'In stock' },
  { id: 'RM-1015', productId: 'PRD-5015', material: 'Contact cement', category: 'Adhesives', quantity: 15, unit: 'cans', reorderPoint: 18, warehouse: 'BuildPro Supplies', unitCost: 275, status: 'Critical' },
  { id: 'RM-1016', productId: 'PRD-5016', material: 'Nails', category: 'Fasteners', quantity: 1850, unit: 'pcs', reorderPoint: 700, warehouse: 'Manila Hardware Co.', unitCost: 1.2, status: 'In stock' },
  { id: 'RM-1017', productId: 'PRD-5017', material: 'Birch plywood', category: 'Panels', quantity: 27, unit: 'sheets', reorderPoint: 25, warehouse: 'Quezon Panel Mart', unitCost: 1450, status: 'Low stock' },
  { id: 'RM-1018', productId: 'PRD-5018', material: 'Metal table frame', category: 'Components', quantity: 31, unit: 'pcs', reorderPoint: 15, warehouse: 'Cavite Woodcraft', unitCost: 1250, status: 'In stock' },
  { id: 'RM-1019', productId: 'PRD-5019', material: 'Sandpaper sheets', category: 'Consumables', quantity: 680, unit: 'pcs', reorderPoint: 250, warehouse: 'BuildPro Supplies', unitCost: 8.5, status: 'In stock' },
  { id: 'RM-1020', productId: 'PRD-5020', material: 'Machine screws', category: 'Fasteners', quantity: 430, unit: 'pcs', reorderPoint: 350, warehouse: 'Manila Hardware Co.', unitCost: 3.8, status: 'Low stock' },

  { id: 'RM-1021', productId: 'PRD-5021', material: 'Mahogany boards', category: 'Lumber', quantity: 58, unit: 'boards', reorderPoint: 30, warehouse: 'Luzon Timber Supply', unitCost: 980, status: 'In stock' },
  { id: 'RM-1022', productId: 'PRD-5022', material: 'Particle boards', category: 'Panels', quantity: 21, unit: 'sheets', reorderPoint: 25, warehouse: 'Quezon Panel Mart', unitCost: 690, status: 'Critical' },
  { id: 'RM-1023', productId: 'PRD-5023', material: 'Shelf brackets', category: 'Hardware', quantity: 73, unit: 'pcs', reorderPoint: 50, warehouse: 'Metro Metalworks', unitCost: 95, status: 'In stock' },
  { id: 'RM-1024', productId: 'PRD-5024', material: 'Satin lacquer', category: 'Finishing', quantity: 29, unit: 'cans', reorderPoint: 25, warehouse: 'ColorCraft Depot', unitCost: 480, status: 'In stock' },
  { id: 'RM-1025', productId: 'PRD-5025', material: 'Epoxy adhesive', category: 'Adhesives', quantity: 12, unit: 'kits', reorderPoint: 20, warehouse: 'BuildPro Supplies', unitCost: 320, status: 'Critical' },
  { id: 'RM-1026', productId: 'PRD-5026', material: 'Drywall screws', category: 'Fasteners', quantity: 920, unit: 'pcs', reorderPoint: 400, warehouse: 'Manila Hardware Co.', unitCost: 2.1, status: 'In stock' },
  { id: 'RM-1027', productId: 'PRD-5027', material: 'Marine plywood', category: 'Panels', quantity: 44, unit: 'sheets', reorderPoint: 30, warehouse: 'Quezon Panel Mart', unitCost: 1680, status: 'In stock' },
  { id: 'RM-1028', productId: 'PRD-5028', material: 'Chair legs', category: 'Components', quantity: 19, unit: 'sets', reorderPoint: 20, warehouse: 'Cavite Woodcraft', unitCost: 560, status: 'Low stock' },
  { id: 'RM-1029', productId: 'PRD-5029', material: 'Polishing pads', category: 'Consumables', quantity: 145, unit: 'pcs', reorderPoint: 60, warehouse: 'BuildPro Supplies', unitCost: 35, status: 'In stock' },
  { id: 'RM-1030', productId: 'PRD-5030', material: 'Anchor bolts', category: 'Fasteners', quantity: 285, unit: 'pcs', reorderPoint: 200, warehouse: 'Manila Hardware Co.', unitCost: 14, status: 'In stock' },

  { id: 'RM-1031', productId: 'PRD-5031', material: 'Teak boards', category: 'Lumber', quantity: 34, unit: 'boards', reorderPoint: 20, warehouse: 'Luzon Timber Supply', unitCost: 1350, status: 'In stock' },
  { id: 'RM-1032', productId: 'PRD-5032', material: 'HDF sheets', category: 'Panels', quantity: 18, unit: 'sheets', reorderPoint: 22, warehouse: 'Quezon Panel Mart', unitCost: 920, status: 'Critical' },
  { id: 'RM-1033', productId: 'PRD-5033', material: 'Corner braces', category: 'Hardware', quantity: 118, unit: 'pcs', reorderPoint: 75, warehouse: 'Metro Metalworks', unitCost: 42, status: 'In stock' },
  { id: 'RM-1034', productId: 'PRD-5034', material: 'Matte finish', category: 'Finishing', quantity: 36, unit: 'cans', reorderPoint: 24, warehouse: 'ColorCraft Depot', unitCost: 395, status: 'In stock' },
  { id: 'RM-1035', productId: 'PRD-5035', material: 'Construction adhesive', category: 'Adhesives', quantity: 26, unit: 'tubes', reorderPoint: 30, warehouse: 'BuildPro Supplies', unitCost: 210, status: 'Low stock' },
  { id: 'RM-1036', productId: 'PRD-5036', material: 'Threaded rods', category: 'Fasteners', quantity: 175, unit: 'pcs', reorderPoint: 100, warehouse: 'Manila Hardware Co.', unitCost: 68, status: 'In stock' },
  { id: 'RM-1037', productId: 'PRD-5037', material: 'Laminated plywood', category: 'Panels', quantity: 33, unit: 'sheets', reorderPoint: 20, warehouse: 'Quezon Panel Mart', unitCost: 1320, status: 'In stock' },
  { id: 'RM-1038', productId: 'PRD-5038', material: 'Cabinet handles', category: 'Hardware', quantity: 84, unit: 'pcs', reorderPoint: 60, warehouse: 'Metro Metalworks', unitCost: 115, status: 'In stock' },
  { id: 'RM-1039', productId: 'PRD-5039', material: 'Steel wool', category: 'Consumables', quantity: 210, unit: 'packs', reorderPoint: 80, warehouse: 'BuildPro Supplies', unitCost: 28, status: 'In stock' },
  { id: 'RM-1040', productId: 'PRD-5040', material: 'Carriage bolts', category: 'Fasteners', quantity: 190, unit: 'pcs', reorderPoint: 220, warehouse: 'Manila Hardware Co.', unitCost: 9.5, status: 'Low stock' },

  { id: 'RM-1041', productId: 'PRD-5041', material: 'Ash boards', category: 'Lumber', quantity: 72, unit: 'boards', reorderPoint: 35, warehouse: 'Luzon Timber Supply', unitCost: 820, status: 'In stock' },
  { id: 'RM-1042', productId: 'PRD-5042', material: 'Cement board', category: 'Panels', quantity: 14, unit: 'sheets', reorderPoint: 18, warehouse: 'Quezon Panel Mart', unitCost: 780, status: 'Critical' },
  { id: 'RM-1043', productId: 'PRD-5043', material: 'T-nuts', category: 'Hardware', quantity: 320, unit: 'pcs', reorderPoint: 150, warehouse: 'Metro Metalworks', unitCost: 6.5, status: 'In stock' },
  { id: 'RM-1044', productId: 'PRD-5044', material: 'Gloss varnish', category: 'Finishing', quantity: 22, unit: 'cans', reorderPoint: 20, warehouse: 'ColorCraft Depot', unitCost: 450, status: 'Low stock' },
  { id: 'RM-1045', productId: 'PRD-5045', material: 'Super glue', category: 'Adhesives', quantity: 64, unit: 'bottles', reorderPoint: 30, warehouse: 'BuildPro Supplies', unitCost: 95, status: 'In stock' },
  { id: 'RM-1046', productId: 'PRD-5046', material: 'Self-tapping screws', category: 'Fasteners', quantity: 610, unit: 'pcs', reorderPoint: 300, warehouse: 'Manila Hardware Co.', unitCost: 3.2, status: 'In stock' },
  { id: 'RM-1047', productId: 'PRD-5047', material: 'OSB panels', category: 'Panels', quantity: 47, unit: 'sheets', reorderPoint: 30, warehouse: 'Quezon Panel Mart', unitCost: 990, status: 'In stock' },
  { id: 'RM-1048', productId: 'PRD-5048', material: 'Bench legs', category: 'Components', quantity: 16, unit: 'sets', reorderPoint: 18, warehouse: 'Cavite Woodcraft', unitCost: 680, status: 'Low stock' },
  { id: 'RM-1049', productId: 'PRD-5049', material: 'Buffing wheels', category: 'Consumables', quantity: 92, unit: 'pcs', reorderPoint: 45, warehouse: 'BuildPro Supplies', unitCost: 75, status: 'In stock' },
  { id: 'RM-1050', productId: 'PRD-5050', material: 'Wing nuts', category: 'Fasteners', quantity: 245, unit: 'pcs', reorderPoint: 120, warehouse: 'Manila Hardware Co.', unitCost: 7.2, status: 'In stock' },

  { id: 'RM-1051', productId: 'PRD-5051', material: 'Beech boards', category: 'Lumber', quantity: 49, unit: 'boards', reorderPoint: 25, warehouse: 'Luzon Timber Supply', unitCost: 910, status: 'In stock' },
  { id: 'RM-1052', productId: 'PRD-5052', material: 'PVC sheets', category: 'Panels', quantity: 28, unit: 'sheets', reorderPoint: 30, warehouse: 'Quezon Panel Mart', unitCost: 640, status: 'Low stock' },
  { id: 'RM-1053', productId: 'PRD-5053', material: 'Flat brackets', category: 'Hardware', quantity: 132, unit: 'pcs', reorderPoint: 80, warehouse: 'Metro Metalworks', unitCost: 55, status: 'In stock' },
  { id: 'RM-1054', productId: 'PRD-5054', material: 'Wood primer', category: 'Finishing', quantity: 17, unit: 'cans', reorderPoint: 20, warehouse: 'ColorCraft Depot', unitCost: 310, status: 'Critical' },
  { id: 'RM-1055', productId: 'PRD-5055', material: 'Silicone sealant', category: 'Adhesives', quantity: 41, unit: 'tubes', reorderPoint: 25, warehouse: 'BuildPro Supplies', unitCost: 165, status: 'In stock' },
  { id: 'RM-1056', productId: 'PRD-5056', material: 'Drywall anchors', category: 'Fasteners', quantity: 540, unit: 'pcs', reorderPoint: 250, warehouse: 'Manila Hardware Co.', unitCost: 2.8, status: 'In stock' },
  { id: 'RM-1057', productId: 'PRD-5057', material: 'Phenolic board', category: 'Panels', quantity: 23, unit: 'sheets', reorderPoint: 25, warehouse: 'Quezon Panel Mart', unitCost: 1250, status: 'Low stock' },
  { id: 'RM-1058', productId: 'PRD-5058', material: 'Furniture casters', category: 'Components', quantity: 65, unit: 'sets', reorderPoint: 30, warehouse: 'Cavite Woodcraft', unitCost: 340, status: 'In stock' },
  { id: 'RM-1059', productId: 'PRD-5059', material: 'Cleaning cloths', category: 'Consumables', quantity: 380, unit: 'pcs', reorderPoint: 150, warehouse: 'BuildPro Supplies', unitCost: 18, status: 'In stock' },
  { id: 'RM-1060', productId: 'PRD-5060', material: 'Lock nuts', category: 'Fasteners', quantity: 310, unit: 'pcs', reorderPoint: 180, warehouse: 'Manila Hardware Co.', unitCost: 5.8, status: 'In stock' },

  { id: 'RM-1061', productId: 'PRD-5061', material: 'Walnut boards', category: 'Lumber', quantity: 26, unit: 'boards', reorderPoint: 22, warehouse: 'Luzon Timber Supply', unitCost: 1550, status: 'Low stock' },
  { id: 'RM-1062', productId: 'PRD-5062', material: 'Acrylic sheets', category: 'Panels', quantity: 36, unit: 'sheets', reorderPoint: 20, warehouse: 'Quezon Panel Mart', unitCost: 720, status: 'In stock' },
  { id: 'RM-1063', productId: 'PRD-5063', material: 'Joining plates', category: 'Hardware', quantity: 105, unit: 'pcs', reorderPoint: 70, warehouse: 'Metro Metalworks', unitCost: 48, status: 'In stock' },
  { id: 'RM-1064', productId: 'PRD-5064', material: 'Wood wax', category: 'Finishing', quantity: 13, unit: 'cans', reorderPoint: 18, warehouse: 'ColorCraft Depot', unitCost: 290, status: 'Critical' },
  { id: 'RM-1065', productId: 'PRD-5065', material: 'PU adhesive', category: 'Adhesives', quantity: 34, unit: 'bottles', reorderPoint: 20, warehouse: 'BuildPro Supplies', unitCost: 380, status: 'In stock' },
  { id: 'RM-1066', productId: 'PRD-5066', material: 'Concrete screws', category: 'Fasteners', quantity: 440, unit: 'pcs', reorderPoint: 250, warehouse: 'Manila Hardware Co.', unitCost: 6.8, status: 'In stock' },
  { id: 'RM-1067', productId: 'PRD-5067', material: 'Melamine boards', category: 'Panels', quantity: 19, unit: 'sheets', reorderPoint: 24, warehouse: 'Quezon Panel Mart', unitCost: 1080, status: 'Critical' },
  { id: 'RM-1068', productId: 'PRD-5068', material: 'Metal drawer handles', category: 'Hardware', quantity: 77, unit: 'pcs', reorderPoint: 50, warehouse: 'Metro Metalworks', unitCost: 135, status: 'In stock' },
  { id: 'RM-1069', productId: 'PRD-5069', material: 'Cutting blades', category: 'Consumables', quantity: 86, unit: 'pcs', reorderPoint: 40, warehouse: 'BuildPro Supplies', unitCost: 145, status: 'In stock' },
  { id: 'RM-1070', productId: 'PRD-5070', material: 'Toggle bolts', category: 'Fasteners', quantity: 175, unit: 'pcs', reorderPoint: 200, warehouse: 'Manila Hardware Co.', unitCost: 8.4, status: 'Low stock' },

  { id: 'RM-1071', productId: 'PRD-5071', material: 'Maple boards', category: 'Lumber', quantity: 63, unit: 'boards', reorderPoint: 30, warehouse: 'Luzon Timber Supply', unitCost: 1080, status: 'In stock' },
  { id: 'RM-1072', productId: 'PRD-5072', material: 'Foam boards', category: 'Panels', quantity: 52, unit: 'sheets', reorderPoint: 25, warehouse: 'Quezon Panel Mart', unitCost: 320, status: 'In stock' },
  { id: 'RM-1073', productId: 'PRD-5073', material: 'Mounting plates', category: 'Hardware', quantity: 91, unit: 'pcs', reorderPoint: 60, warehouse: 'Metro Metalworks', unitCost: 72, status: 'In stock' },
  { id: 'RM-1074', productId: 'PRD-5074', material: 'Sanding sealer', category: 'Finishing', quantity: 16, unit: 'cans', reorderPoint: 20, warehouse: 'ColorCraft Depot', unitCost: 365, status: 'Critical' },
  { id: 'RM-1075', productId: 'PRD-5075', material: 'Hot melt glue', category: 'Adhesives', quantity: 230, unit: 'sticks', reorderPoint: 100, warehouse: 'BuildPro Supplies', unitCost: 14, status: 'In stock' },
  { id: 'RM-1076', productId: 'PRD-5076', material: 'Lag screws', category: 'Fasteners', quantity: 265, unit: 'pcs', reorderPoint: 180, warehouse: 'Manila Hardware Co.', unitCost: 11.5, status: 'In stock' },
  { id: 'RM-1077', productId: 'PRD-5077', material: 'Fire-rated plywood', category: 'Panels', quantity: 12, unit: 'sheets', reorderPoint: 15, warehouse: 'Quezon Panel Mart', unitCost: 1980, status: 'Critical' },
  { id: 'RM-1078', productId: 'PRD-5078', material: 'Furniture wheels', category: 'Components', quantity: 48, unit: 'sets', reorderPoint: 30, warehouse: 'Cavite Woodcraft', unitCost: 420, status: 'In stock' },
  { id: 'RM-1079', productId: 'PRD-5079', material: 'Wire brushes', category: 'Consumables', quantity: 74, unit: 'pcs', reorderPoint: 35, warehouse: 'BuildPro Supplies', unitCost: 42, status: 'In stock' },
  { id: 'RM-1080', productId: 'PRD-5080', material: 'Rivets', category: 'Fasteners', quantity: 560, unit: 'pcs', reorderPoint: 250, warehouse: 'Manila Hardware Co.', unitCost: 2.6, status: 'In stock' },

  { id: 'RM-1081', productId: 'PRD-5081', material: 'Cedar boards', category: 'Lumber', quantity: 41, unit: 'boards', reorderPoint: 30, warehouse: 'Luzon Timber Supply', unitCost: 880, status: 'In stock' },
  { id: 'RM-1082', productId: 'PRD-5082', material: 'Hardboard sheets', category: 'Panels', quantity: 17, unit: 'sheets', reorderPoint: 20, warehouse: 'Quezon Panel Mart', unitCost: 540, status: 'Critical' },
  { id: 'RM-1083', productId: 'PRD-5083', material: 'Furniture brackets', category: 'Hardware', quantity: 124, unit: 'pcs', reorderPoint: 70, warehouse: 'Metro Metalworks', unitCost: 62, status: 'In stock' },
  { id: 'RM-1084', productId: 'PRD-5084', material: 'Danish oil', category: 'Finishing', quantity: 24, unit: 'cans', reorderPoint: 18, warehouse: 'ColorCraft Depot', unitCost: 520, status: 'In stock' },
  { id: 'RM-1085', productId: 'PRD-5085', material: 'Rubber adhesive', category: 'Adhesives', quantity: 19, unit: 'cans', reorderPoint: 22, warehouse: 'BuildPro Supplies', unitCost: 240, status: 'Low stock' },
  { id: 'RM-1086', productId: 'PRD-5086', material: 'Pan head screws', category: 'Fasteners', quantity: 720, unit: 'pcs', reorderPoint: 350, warehouse: 'Manila Hardware Co.', unitCost: 2.9, status: 'In stock' },
  { id: 'RM-1087', productId: 'PRD-5087', material: 'Birch panels', category: 'Panels', quantity: 31, unit: 'sheets', reorderPoint: 25, warehouse: 'Quezon Panel Mart', unitCost: 1380, status: 'In stock' },
  { id: 'RM-1088', productId: 'PRD-5088', material: 'Desk legs', category: 'Components', quantity: 22, unit: 'sets', reorderPoint: 25, warehouse: 'Cavite Woodcraft', unitCost: 780, status: 'Low stock' },
  { id: 'RM-1089', productId: 'PRD-5089', material: 'Abrasive belts', category: 'Consumables', quantity: 116, unit: 'pcs', reorderPoint: 50, warehouse: 'BuildPro Supplies', unitCost: 85, status: 'In stock' },
  { id: 'RM-1090', productId: 'PRD-5090', material: 'Threaded inserts', category: 'Fasteners', quantity: 385, unit: 'pcs', reorderPoint: 180, warehouse: 'Manila Hardware Co.', unitCost: 7.5, status: 'In stock' },

  { id: 'RM-1091', productId: 'PRD-5091', material: 'Red oak boards', category: 'Lumber', quantity: 57, unit: 'boards', reorderPoint: 30, warehouse: 'Luzon Timber Supply', unitCost: 1120, status: 'In stock' },
  { id: 'RM-1092', productId: 'PRD-5092', material: 'Composite panels', category: 'Panels', quantity: 25, unit: 'sheets', reorderPoint: 28, warehouse: 'Quezon Panel Mart', unitCost: 1160, status: 'Low stock' },
  { id: 'RM-1093', productId: 'PRD-5093', material: 'Metal corner plates', category: 'Hardware', quantity: 88, unit: 'pcs', reorderPoint: 50, warehouse: 'Metro Metalworks', unitCost: 58, status: 'In stock' },
  { id: 'RM-1094', productId: 'PRD-5094', material: 'Polyurethane finish', category: 'Finishing', quantity: 20, unit: 'cans', reorderPoint: 22, warehouse: 'ColorCraft Depot', unitCost: 610, status: 'Low stock' },
  { id: 'RM-1095', productId: 'PRD-5095', material: 'Spray adhesive', category: 'Adhesives', quantity: 14, unit: 'cans', reorderPoint: 20, warehouse: 'BuildPro Supplies', unitCost: 295, status: 'Critical' },
  { id: 'RM-1096', productId: 'PRD-5096', material: 'Socket screws', category: 'Fasteners', quantity: 510, unit: 'pcs', reorderPoint: 250, warehouse: 'Manila Hardware Co.', unitCost: 5.2, status: 'In stock' },
  { id: 'RM-1097', productId: 'PRD-5097', material: 'Laminated MDF', category: 'Panels', quantity: 42, unit: 'sheets', reorderPoint: 25, warehouse: 'Quezon Panel Mart', unitCost: 950, status: 'In stock' },
  { id: 'RM-1098', productId: 'PRD-5098', material: 'Furniture feet', category: 'Components', quantity: 68, unit: 'sets', reorderPoint: 35, warehouse: 'Cavite Woodcraft', unitCost: 230, status: 'In stock' },
  { id: 'RM-1099', productId: 'PRD-5099', material: 'Polishing compound', category: 'Consumables', quantity: 34, unit: 'bottles', reorderPoint: 20, warehouse: 'BuildPro Supplies', unitCost: 185, status: 'In stock' },
  { id: 'RM-1100', productId: 'PRD-5100', material: 'Cap nuts', category: 'Fasteners', quantity: 205, unit: 'pcs', reorderPoint: 150, warehouse: 'Manila Hardware Co.', unitCost: 6.4, status: 'In stock' },

  { id: 'RM-1101', productId: 'PRD-5101', material: 'Douglas fir boards', category: 'Lumber', quantity: 45, unit: 'boards', reorderPoint: 30, warehouse: 'Luzon Timber Supply', unitCost: 760, status: 'In stock' },
  { id: 'RM-1102', productId: 'PRD-5102', material: 'Insulation boards', category: 'Panels', quantity: 16, unit: 'sheets', reorderPoint: 20, warehouse: 'Quezon Panel Mart', unitCost: 890, status: 'Critical' },
  { id: 'RM-1103', productId: 'PRD-5103', material: 'L-brackets', category: 'Hardware', quantity: 150, unit: 'pcs', reorderPoint: 80, warehouse: 'Metro Metalworks', unitCost: 35, status: 'In stock' },
  { id: 'RM-1104', productId: 'PRD-5104', material: 'Shellac finish', category: 'Finishing', quantity: 27, unit: 'cans', reorderPoint: 20, warehouse: 'ColorCraft Depot', unitCost: 430, status: 'In stock' },
  { id: 'RM-1105', productId: 'PRD-5105', material: 'Wood filler', category: 'Adhesives', quantity: 23, unit: 'tubes', reorderPoint: 25, warehouse: 'BuildPro Supplies', unitCost: 125, status: 'Low stock' },
  { id: 'RM-1106', productId: 'PRD-5106', material: 'Fine thread screws', category: 'Fasteners', quantity: 640, unit: 'pcs', reorderPoint: 300, warehouse: 'Manila Hardware Co.', unitCost: 3.6, status: 'In stock' },
  { id: 'RM-1107', productId: 'PRD-5107', material: 'Decorative panels', category: 'Panels', quantity: 29, unit: 'sheets', reorderPoint: 20, warehouse: 'Quezon Panel Mart', unitCost: 1420, status: 'In stock' },
  { id: 'RM-1108', productId: 'PRD-5108', material: 'Metal cabinet feet', category: 'Components', quantity: 37, unit: 'sets', reorderPoint: 25, warehouse: 'Cavite Woodcraft', unitCost: 310, status: 'In stock' },
  { id: 'RM-1109', productId: 'PRD-5109', material: 'Dust masks', category: 'Consumables', quantity: 175, unit: 'pcs', reorderPoint: 100, warehouse: 'BuildPro Supplies', unitCost: 22, status: 'In stock' },
  { id: 'RM-1110', productId: 'PRD-5110', material: 'Flange nuts', category: 'Fasteners', quantity: 155, unit: 'pcs', reorderPoint: 180, warehouse: 'Manila Hardware Co.', unitCost: 6.9, status: 'Low stock' },
];

export const mockRawMaterialMovements: RawMaterialMovement[] = [
  { id: 'MOV-1001-01', materialId: 'RM-1001', type: 'Stock in', quantity: 280, unit: 'pcs', date: '12 Aug, 2026', reference: 'PO-8841', handledBy: 'Juan' },
  { id: 'MOV-1001-02', materialId: 'RM-1001', type: 'Stock out', quantity: 120, unit: 'pcs', date: '10 Aug, 2026', reference: 'JOB-2140', handledBy: 'Miguel' },
  { id: 'MOV-1001-03', materialId: 'RM-1001', type: 'Adjustment', quantity: 15, unit: 'pcs', date: '08 Aug, 2026', reference: 'ADJ-018', handledBy: 'Lara' },
  { id: 'MOV-1002-01', materialId: 'RM-1002', type: 'Stock in', quantity: 24, unit: 'boards', date: '11 Aug, 2026', reference: 'PO-8842', handledBy: 'Angela' },
  { id: 'MOV-1002-02', materialId: 'RM-1002', type: 'Stock out', quantity: 12, unit: 'boards', date: '09 Aug, 2026', reference: 'JOB-2144', handledBy: 'Paolo' },
  { id: 'MOV-1003-01', materialId: 'RM-1003', type: 'Stock out', quantity: 48, unit: 'pcs', date: '12 Aug, 2026', reference: 'JOB-2151', handledBy: 'Rina' },
  { id: 'MOV-1003-02', materialId: 'RM-1003', type: 'Stock in', quantity: 96, unit: 'pcs', date: '07 Aug, 2026', reference: 'PO-8837', handledBy: 'Juan' },
  { id: 'MOV-1004-01', materialId: 'RM-1004', type: 'Stock out', quantity: 8, unit: 'bottles', date: '12 Aug, 2026', reference: 'JOB-2154', handledBy: 'Miguel' },
  { id: 'MOV-1004-02', materialId: 'RM-1004', type: 'Adjustment', quantity: 2, unit: 'bottles', date: '06 Aug, 2026', reference: 'ADJ-021', handledBy: 'Lara' },
  { id: 'MOV-1005-01', materialId: 'RM-1005', type: 'Stock out', quantity: 6, unit: 'cans', date: '11 Aug, 2026', reference: 'JOB-2148', handledBy: 'Angela' },
  { id: 'MOV-1005-02', materialId: 'RM-1005', type: 'Stock out', quantity: 4, unit: 'cans', date: '08 Aug, 2026', reference: 'JOB-2135', handledBy: 'Paolo' },
  { id: 'MOV-1006-01', materialId: 'RM-1006', type: 'Stock in', quantity: 18, unit: 'sheets', date: '10 Aug, 2026', reference: 'PO-8839', handledBy: 'Rina' },
  { id: 'MOV-1007-01', materialId: 'RM-1007', type: 'Stock out', quantity: 20, unit: 'pairs', date: '12 Aug, 2026', reference: 'JOB-2153', handledBy: 'Juan' },
  { id: 'MOV-1008-01', materialId: 'RM-1008', type: 'Stock in', quantity: 16, unit: 'pcs', date: '09 Aug, 2026', reference: 'PO-8838', handledBy: 'Miguel' },
  { id: 'MOV-1009-01', materialId: 'RM-1009', type: 'Stock out', quantity: 80, unit: 'pcs', date: '11 Aug, 2026', reference: 'JOB-2149', handledBy: 'Lara' },
  { id: 'MOV-1010-01', materialId: 'RM-1010', type: 'Stock in', quantity: 240, unit: 'pcs', date: '07 Aug, 2026', reference: 'PO-8836', handledBy: 'Angela' },
]

export const rawMaterialSortOptions: RawMaterialSortOption[] = [
  {
    label: 'Material (A → Z)',
    value: 'material',
    order: 'asc',
  },
  {
    label: 'Material (Z → A)',
    value: 'material',
    order: 'desc',
  },
  {
    label: 'Quantity (High → Low)',
    value: 'quantity',
    order: 'desc',
  },
  {
    label: 'Quantity (Low → High)',
    value: 'quantity',
    order: 'asc',
  },
  {
    label: 'Reorder Point',
    value: 'reorderPoint',
    order: 'desc',
  },
  {
    label: 'Unit Cost',
    value: 'unitCost',
    order: 'desc',
  },
  {
    label: 'Warehouse',
    value: 'warehouse',
    order: 'asc',
  },
]
